const Actions = {
  HELLO_WORLD: "HELLO_WORLD",
  GET_BPM: "GET_BPM",
  SET_BPM: "SET_BPM",
  IS_PLAYING: "IS_PLAYING",
  SET_PLAY: "SET_PLAY",
  GET_SEQUENCE: "GET_SEQUENCE",
  ADD_SEQUENCE: "ADD_SEQUENCE",
  DELETE_SEQUENCE: "DELETE_SEQUENCE",
  SET_SELECTED_SEQUENCE: "SET_SELECTED_SEQUENCE",
  GET_PATTERNS: "GET_PATTERNS",
  ADD_PATTERN: "ADD_PATTERN",
  REMOVE_PATTERN: "REMOVE_PATTERN",
};

export default Actions;
