const Actions = {
  LOAD_DATA: "LOAD_DATA",
  GET_BPM: "GET_BPM",
  SET_BPM: "SET_BPM",
  IS_PLAYING: "IS_PLAYING",
  SET_PLAY: "SET_PLAY",
  GET_SEQUENCE: "GET_SEQUENCE",
  ADD_SEQUENCE: "ADD_SEQUENCE",
  DELETE_SEQUENCE: "DELETE_SEQUENCE",
  SET_SELECTED_SEQUENCE: "SET_SELECTED_SEQUENCE",
  GET_PATTERNS: "GET_PATTERNS",
  ADD_PATTERN: "ADD_PATTERN",
  REMOVE_PATTERN: "REMOVE_PATTERN",
  UPDATE_SINGLE_STEP: "UPDATE_SINGLE_STEP",
  UPDATE_ALL_STEPS_ON_BEAT: "UPDATE_ALL_STEPS_ON_BEAT",
  UPDATE_TIMER_ID: "UPDATE_TIMER_ID",
  UPDATE_COLUMN_COUNT: "UPDATE_COLUMN_COUNT",
};

export default Actions;
